### ISSUE TITLE
Try except manquant, des donnees peuvent etre mal formatee ou des champs peuvent ne pas du tout exister

### ISSUE THREAD

**Issue by aiwanesk** [Christophe-Dupin/P5-OPENFOODFACT#1]
https://github.com/Christophe-Dupin/P5-OPENFOODFACT/blob/f4e93335e4faf24d7d5cffffdde73eda6e1fbbc5/app/controller/controller.py#L46

**Comment by Christophe-Dupin** [comment]
done
